all: test
.PHONY: test

CFLAGS= -g -pg -Os -Wall -I. -I./test/ -DZC_DEBUG
LIBS= -L. -lzc-debug -lpthread -lrt -ldb -lssl -lcrypto -lmysqlclient

SRC=${shell find test -type f -name "*.c"}
OBJS := $(SRC:.c=)

$(OBJS): libzc-debug.a test/test_lib.h

.c:
	gcc $*.c $(CFLAGS) $(LIBS) -o $*

test:  $(OBJS)

clean:
	rm -f  $(OBJS)
