SUFFIX_LIBS = 
LIB_io = -lrt -lssl -lcrypto -lz -lpthread -ldl
LIB_mem_io = -lrt -lssl -lcrypto -lz -lpthread -ldl
LIB_test = -lrt -lssl -lcrypto -lz -lpthread -ldl
include ../../makefiles/sample.makefile
