${shell mkdir -p uploaded_files; }
DELS=uploaded_files
SUFFIX_LIBS = -lssl -lcrypto
coroutine_httpd_LIB = ../../libzc_coroutine.a
LIB_coroutine_httpd = -lpthread
include ../../makefiles/sample.makefile
$(DEST): ./lib_httpd.h
